In [108]:
# for installing the numpy 
!pip install numpy

#import numpy module with alias np
import numpy as np

In [110]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
a = np.array([1,2,3,4,'a'])


In [111]:
# print a
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [112]:
# define a,b,c and d as instructed above
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [113]:
#print dimentions of a,b, c and d
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [ ]:
# print shape of each a,b ,c and d
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

In [114]:
# print data type of c and d
print(c.dtype)
print(d.dtype)

int32
int32


In [115]:
# Lets check length of array b, using len() function
len(d)

2

In [116]:
#print type of a and b variable
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [117]:
# Lets check length of array b, using len() function
len(d)

2

In [ ]:
# create an array using arange passing 1, 11 and 2 as parameters
np.arange(1,11,2)

In [ ]:
# create numpy array using eye function with 3 as passed parameter
np.eye(2, dtype = float)

In [ ]:
# create a numpy array using zero function with (3,2) as passed parameter takes default float 
np.zeros((3,5),dtype="int") # defalut float

In [ ]:
#create a numpy array using full function with (3,2) and 2 as passed parameter
np.full((2,3),111,dtype=int)


In [ ]:
# create a numpy array using diag function passing a list[1,2,3,4,5]
x= [1,2,3,4,5,6,7]
np.diag(x)


In [118]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [119]:
# Reshape x with 2 rows and 8 columns
n=x.reshape((8,2)) # 1d
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [120]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [ ]:
# convert to old dimension
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

In [ ]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
print(x)
x.reshape((2,8))

In [ ]:
# Flattening x convert array into one dimensional
x.flatten()

In [ ]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)

# print a
a

In [ ]:
# Get third element in array a
a[2]

In [ ]:
#Print 3rd, 5th, and 7th element in array a
a[0:7:2]

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
# print the 3rd element from the 3rd row of a
a[2,2]

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
b[1][1][2]

In [ ]:
arr=np.arange(1,11)
arr

In [ ]:
# Slice elements from 1st to 5th element from array arr:
arr[0:5]

In [ ]:
# Slice elements from index 5 to the end of the array arr:
arr[5:]

In [ ]:
# Slice elements from the beginning to index 5 (not included) in array arr:
arr[0:5]

In [ ]:
# Print every other element from index 1 to index 7:
arr[1:7:2]

In [ ]:
# Return every other element from the entire array arr:
arr[0:10:2]

In [ ]:
# Print array a
a

In [ ]:
# In array 'a' print index 2 from all the rows :
arr[2]

In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a[0:,1:]

In [ ]:
x1= np.arange(10)
x1

In [ ]:
# assign x2 = x1
x2 = x1 # view 

In [ ]:
#print x1 and x2
print(x1)
print(x2)

In [ ]:
# change 1st element of x2 as 10
x2[0] = 10

In [ ]:
#Again print x1 and x2
print(x1)
print(x2)

In [ ]:
# memory check
print(id(x1))
print(id(x2))

In [ ]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

In [ ]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

In [ ]:
# Again check memory share between x1 and x3
np.shares_memory(x1, x3)

In [ ]:
#Change 1st element of x3=100
x3[0] = 100

In [ ]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

In [ ]:
# Now create an array x4 which is copy of x1

x4 = np.copy(x1)

In [ ]:
# Change the last element of x4 as 900
x4[-1] = 900

In [ ]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

In [ ]:
#Check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1, x4)

In [ ]:
#print a
a

In [ ]:
# Check if every element in array a greater than 3 or not Using '>' notation
a > 3

In [ ]:
# Get a list with all elements of array 'a' grater than 3
a[a > 3]

In [ ]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
a[(a > 3) & (a < 6)]

In [ ]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation
x1 == x4
# print(x1)
# print(x4)

In [ ]:
# Print Transpose of array 'a'
print(a.transpose())
#print array 'a'
print("-----------------")
print(a) 

In [ ]:
# stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1, 4, x4)

In [ ]:
#defining a
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# print trigonometric sin value of each element of a
np.sin(a)

In [ ]:
(np.sin(a))/(np.cos(a))

In [ ]:
# print trigonometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

In [ ]:
# Print exponential value of each elements of a
np.exp(a)

In [ ]:
# print total sum of elements of a
np.sum(a)

In [ ]:
# Print sum in array a column wise
np.sum(a, axis=1)

In [ ]:
# Print sum in array a row wise
np.sum(a, axis=0)

In [ ]:
# print median of array a
np.median(a)

In [ ]:
# print standard deviation of array a
np.std(a)

In [ ]:
#print largest element present in array a
np.max(a)

In [ ]:
# print sorted x4 array
np.sort(x4)

In [ ]:
# print the indexes where the value is 4 in array x1

m=np.where(x1 == 4)
m

In [ ]:
#print array x1
x1

In [ ]:
c=np.array([44,55,66,88,99,12,12,12,12,12,10,10,10,101,0])

In [ ]:
# Print the indexes where the values are even in array x1
np.where(c%2 == 0)

In [ ]:
# Print x1 where x1 is greater than 5, also if number is less than 5 then replace it with 0

np.where(x1>5, x1, 0)

In [105]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [106]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [107]:
print(dir(tuple))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
